exclude: ^(\.eggs|\.git|\.tox|__pycache__/|env/|\.pytest_cache|build/|dist/|examples/)
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
