# https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.8.3-buster-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "setup.py" }}
            - v4-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -e .[dev]

      - save_cache:
          paths:
            - ./venv
          key: v4-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir -p results/pytest
            pytest --cov=htexpr --cov-report=html --junitxml=results/pytest/junit.xml tests
            pytest --headless examples

      - store_test_results:
          path: results

      - store_artifacts:
          path: htmlcov
          destination: htmlcov
