# https://circleci.com/docs/2.0/language-python/
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/python
      - image: cimg/python:3.10.4-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-browser-tools
      - checkout

      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "setup.py" }}
            - v5-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -e .[dev]

      - save_cache:
          paths:
            - ./venv
          key: v5-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir -p results/pytest
            coverage erase
            coverage run -m pytest tests
            coverage html
            coverage xml -o results/pytest/junit.xml
            pytest --headless examples

      - store_test_results:
          path: results

      - store_artifacts:
          path: htmlcov
          destination: htmlcov
