name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
        - 3.8
        - 3.9
        - "3.10"
        - "3.11"
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Store pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.OS }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            pip-${{ runner.OS }}-${{ matrix.python-version }}-
            pip-${{ runner.OS }}-
            pip-
      - name: Install prerequisites
        run: sudo apt-get install libxml2-dev libxslt1-dev
        if: matrix.python-version == 'pypy3'
      - name: Install
        run: |
          python3 -m pip install -U pip wheel
          python3 -m pip install -e .[dev]
      - name: Run tests
        run: |
          mkdir -p results/pytest
          coverage erase
          coverage run -m pytest tests
          coverage html
          coverage xml -o results/pytest/junit.xml
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            results
            htmlcov
